const mostrar = () =>{
    return "<div>"
            +"<di id=\"\" class=\"div-class\" >"
                +"<header>"
                    +"<di>"
                        +"<img src=\"img/Ubicacion.png\" width=\"100\" height=\"100\" alt=\"Logo de empresa\">"
                        +"<h1>Restaurantes</h1>"
                    +"</div>"
                    +"<div>"
                        +"<nav>"
                            +"<div class=\"nav-main\">"
                                +"<ul class=\"menu\">"
                                    +"<li>"+"<a href=\"busqueda.html\">Buscar</a>"+"<li>"
                                    +"<li><a href=\"restaurantes.html\">Restaurantes</a></li>"
                                    +"<li><a href=\"nuevoResturante.html\" >Registrar restaura</a></li>"
                                    +"<li><a href=\"index.html\" >Inicion</a></li>"
                                +"<ul>"
                            +"</div>"
                        +"<nav>"
                    +"</div>"
                +"</header>"
            +"</div>"
            +"<div id=\"\" class=\"div-class\" >"
                +"<form action=\"Controlador\" method=\"POST\" name=\"formulario\">"
                    +"<label for=\"nombre\" class=\"label\" >Nombre</label><br>"
                    +"<input id=\"d1\" type=\"text\" name=\"nombre\" class=\"campo\" placeholder=\"nombre\" autocomplete=\"true\" size=\"100\"><br>"
                    +"<label for=\"descripcion\" class=\"label\" >Descripcion</label><br>"
                    +"<textarea id=\"d2\" type=\"text\" name=\"descripcion\" class=\"campo\" placeholder=\"descripcion\" autocomplete=\"true\"></textarea><br>"
                    +"<label for=\"direccion\" class=\"label\" >Direccion</label><br>"
                    +"<input id=\"d3\" type=\"text\" name=\"direccion\" class=\"campo\" placeholder=\"direccion\" autocomplete=\"true\" size=\"100\"><br>"
                    +"<label for=\"imagen\" class=\"label\" >Imagen</label><br>"
                    +"<input id=\"d4\" type=\"file\" name=\"imagen\" class=\"campo\" placeholder=\"imagen\"><br>"
                    +"<button type=\"submit\" class=\"button\" action=\"guardar\" value=\"valores\" >Enviar</button><br>"
                    +"<button type=\"reset\" class=\"button\">Borrar</button>"
                +"</form>"
            +"</div>"
            +"</div>"              
}

document.write(mostrar())