const mostrar = () =>{
    return "<div id=\"the-div-index\">"
            +"<di>"
                +"<header class=\"div-margin\">"
                    +"<di>"
                        +"<img src=\"img/Ubicacion.png\" width=\"100\" height=\"100\" alt=\"Logo de empresa\">"
                        +"<h1>Restaurantes</h1>"
                    +"</div>"
                    +"<div>"
                        +"<nav>"
                            +"<div class=\"nav-main\">"
                                +"<ul class=\"menu\">"
                                    +"<li>"+"<a href=\"busqueda.html\">Buscar</a>"+"<li>"
                                    +"<li><a href=\"restaurantes.html\">Restaurantes</a></li>"
                                    +"<li><a href=\"nuevoResturante.html\" >Registrar restaura</a></li>"
                                +"<ul>"
                            +"</div>"
                        +"<nav>"
                    +"</div>"
                +"</header>"
            +"</div>"
            +"<div >"
                +"<section id=\"section\" class=\"div-margin\">"
                    +"<picture id=\"the-picture\">"
                        +"<img class=\"the-img\" src=\"img/En-todo-mundo.png\" width=\"500\" height=\"300\" alt=\"Logo de Presentacion\">"
                        +"<img class=\"the-img\" src=\"img/Trato.png\" width=\"500\" height=\"300\" alt=\"Logo de Presentacion\">"
                        +"<p>Somos un puente que conecta personas con las mejores experiencias gastronomicas<br><strong>estamos felices de brindarle  los mejores restaurantes,</strong><br>cada dia nos procuramos de ofrecer las mejores experiencias.</p>"
                    +"</picture>>"
                +"</section>"
            +"</div>"
            +"</div>"              
}

document.write(mostrar())